# Generated by Django 4.2.16 on 2024-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudge', '0002_remove_businfomodel_bus_stop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('cancelled', 'Cancelled')], max_length=15)),
                ('bus_delay_time', models.CharField(choices=[('0-5', 'Less than 5 minutes'), ('5-10', 'Between 5 and 10 minutes'), ('10-20', 'between 10 and 20 minutes'), ('20+', 'More than 20 minutes')], max_length=30)),
            ],
        ),
    ]
