# Generated by Django 4.2.16 on 2024-10-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudge', '0004_busreportmodel_bus_report_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreportmodel',
            name='bus_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fudge.businfomodel'),
        ),
    ]
